//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaintTintingDesktopApp.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public int PaintId { get; set; }
        public int NumberOfPaint { get; set; }
        public int CustomerId { get; set; }
        public int SellerId { get; set; }
        public System.DateTime DateTime { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Paint Paint { get; set; }
        public virtual User User { get; set; }
    }
}
