//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaintTintingDesktopApp.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paint()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public string ColorAsHex { get; set; }
        public string ProductName { get; set; }
        public int PaintProviderId { get; set; }
        public int PackagingInLiters { get; set; }
        public decimal PriceInRubles { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        public virtual PaintProvider PaintProvider { get; set; }
    }
}
